version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  llm:
    provider:
      type: model
      options:
        model: ai/gemma3

volumes:
  ollama_data: